com.dwarfeng.statistics.jdbc.driver=com.mysql.cj.jdbc.Driver
com.dwarfeng.statistics.jdbc.url=\
  jdbc:mysql://your-host-here:3306/statistics?serverTimezone=Asia/Shanghai&autoReconnect=true
com.dwarfeng.statistics.jdbc.username=root
com.dwarfeng.statistics.jdbc.password=your-password-here
com.dwarfeng.statistics.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
